name       : keyutils
version    : 1.5.11
release    : 2
source     :
    - https://people.redhat.com/~dhowells/keyutils/keyutils-1.5.11.tar.bz2 : 11584488206edc30736263eb855bf7793f16e661987241d333d3cb5ea479b1b5
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : system.utils
summary    : In-kernel key management utilities
description: |
    The keyutils package is a library and a set of utilities for accessing the kernel keyrings facility.
patterns   :
    - devel :
        - /usr/share/man/man3
builddeps  :
    - pkgconfig(krb5)
build      : |
    %make
install    : |
    %make_install NO_ARLIB=1 SBINDIR=%PREFIX%/sbin BINDIR=%PREFIX%/bin LIBDIR=%libdir%

    install -Dm00644 $pkgfiles/keyutils.pc $installdir/usr/lib64/pkgconfig/keyutils.pc
