name       : keyutils
version    : 1.5.10
release    : 1
source     :
    - http://people.redhat.com/~dhowells/keyutils/keyutils-1.5.10.tar.bz2 : 115c3deae7f181778fd0e0ffaa2dad1bf1fe2f5677cf2e0e348cdb7a1c93afb6
license    :
    - GPL-2.0
    - LGPL-2.1
component  : system.utils
summary    : In-kernel key management utilities
description: |
    The keyutils package is a library and a set of utilities for accessing the kernel keyrings
    facility.
build      : |
    %make
install    : |
    %make_install NO_ARLIB=1 SBINDIR=/usr/sbin BINDIR=/usr/bin LIBDIR=%libdir%

    install -D -m00644 $pkgfiles/keyutils.pc $installdir/usr/lib64/pkgconfig/keyutils.pc
patterns   :
    - devel:
        - /usr/share/man/man3
